### ISSUE TITLE
New release of geozero-shp?

### ISSUE THREAD

**Issue by grim7reaper** [georust/geozero#230]
Would it be possible to release a new version of geozero-shp?

Seems like the last one available on crates.io is 0.4 which depends on geozero 0.9 which doesn't seems compatible with geozero 0.13 and thus make the interoperability quite painful 😁

**Comment by kylebarron** [comment]
Ref https://github.com/georust/geozero/issues/187. If geozero-shp stays separate, we'll have this issue again with the next geozero release unless geozero-shp is always released at the same time

**Comment by pka** [comment]
Had the same thought. I plan to make a release and doing s PR for merging into  the geozero craze.
