### ISSUE TITLE
Getting geometry and properties from shp file features

### ISSUE THREAD

**Issue by nk9** [georust/geozero#245]
I have a shapefile. I want to iterate through all of its features with the properties for each. I am going to create a bunch of structs in memory using the data and run operations on them, like getting the area of the geometry and examining properties of each feature. So I need the feature geometries in a format that will work with `geo`'s `unsigned_area` method.

The `ShpReader::iter_features()` function [seems like the one I want](https://docs.rs/geozero/latest/geozero/shp/reader/struct.ShpReader.html#method.iter_features):

> Returns an iterator over the Shapes and their Records

I have examined the [shp tests](https://github.com/georust/geozero/blob/771609474a57e19fde9fdfc03454f1b04613e93d/geozero/tests/shp-reader.rs) to figure out how to use it.

This works for the properties:

```rust
use geozero::shp::ShpReader;
use geozero::{FeatureProperties, ProcessorSink};

fn main() -> Result<(), geozero::shp::Error> {
    let reader = ShpReader::from_path("/path/to/my_shapefile.shp")?;

    for feat in reader.iter_features(&mut ProcessorSink::new())? {
        if let Ok(feat) = feat {
            let props = feat.properties()?;
            println!("{props:?}");
        }
    }

    Ok(())
}
```

But I don't see any way to get the geometries (the `Shape`?) from `feat`. The only field in the `ShapeRecord` is `record` (a `dbase::Record`, which seems to be a key-value data structure), and [the only functions in associated traits](https://docs.rs/geozero/latest/geozero/shp/reader/struct.ShapeRecord.html#trait-implementations) have to do with properties.

Do I actually have to use `iter_geometries` as well? Am I missing something here? I don't see any tests or documentation on how to access geometries from the `iter_features()` function of a `ShpReader`.

**Comment by kylebarron** [comment]
It looks like `iter_features` should automatically pass through the geometries as well: https://github.com/georust/geozero/blob/771609474a57e19fde9fdfc03454f1b04613e93d/geozero/tests/shp-reader.rs#L54

**Comment by michaelkirk** [comment]
You could also consider using the shapefile-rs crate directly, rather than geozero: 

https://github.com/tmontaigu/shapefile-rs/tree/master/examples/geotype-example

https://docs.rs/shapefile/latest/shapefile/reader/index.html

In particular, note the `geo-types` feature, which allows you to get the same structs that the `geo` crate uses, so you can call `unsigned_area` (etc.)

**Comment by nk9** [comment]
Thanks for the super quick reply. I am hoping I really don't have to turn these features into GeoJSON first! Is `GeoWriter` the right one for this use case? I do see [one example](https://github.com/georust/geozero/blob/771609474a57e19fde9fdfc03454f1b04613e93d/geozero/tests/shp-reader.rs#L73) of using that in shp-reader, but trying to copy that code into place doesn't compile:

```rust
use geo_types::Geometry;
use geozero::geo_types::GeoWriter;
use geozero::shp::ShpReader;

fn main() -> Result<(), geozero::shp::Error> {
    let reader = ShpReader::from_path("/path/to/my_shapefile.shp")?;
    let mut geo = GeoWriter::new();

    for feat in reader.iter_features(&mut geo)? {
        if let Ok(feat) = feat {
            if let Some(Geometry::GeometryCollection(geo_types::GeometryCollection(gc))) =
                geo.take_geometry()
            {
                println!("{}", gc.len());
            } else {
                panic!("unexpected geometry");
            }
        }
    }

    Ok(())
}
```

This fails with the error: **cannot borrow `geo` as mutable more than once at a time**, with the second mutable borrow called out as the call to `geo.take_geometry()`. Clearly, the borrow checker doesn't like that inside the `for` loop.

In the test, all that happens in the loop is counting. Once all the geometry is written, `take_geometry()` is called, which it seems takes all the Geometry features and puts them in a Vec. When I move the GeometryCollection code above after the for loop, it works. But that defeats the purpose of what I'm trying to do: iterate through the features and the geometry simultaneously.

Am I missing a solution that gives me access to both of these together?

**Comment by nk9** [comment]
Whoops, I just noticed @michaelkirk's reply! I actually started with the shapefile-rs solution, and got that working. But I was having to manually convert from `shapefile::Shape::Polygon` to `geo::Polygon`, so I thought I should instead be using a solution that read in the polygon in the format I ultimately needed it. Perhaps what I'm doing here is more convoluted than necessary, but I couldn't figure out how to get a feature I could reproject or use `unsigned_area` etc on without building one from scratch like this. Feels quite hacky.

```rust
use geo::{coord, CoordsIter, Polygon};
use shapefile::dbase::FieldValue;
use shapefile::{Reader, Shape};

// My own classes
mod ed;
use ed::Ed;

mod feature;
use feature::Feature;

// ...

fn read_shapefile(path: &str) -> Result<Vec<Feature>> {
    let mut reader = Reader::from_path(path)?;
    let mut features = Vec::new();

    for (i, record) in reader.iter_shapes_and_records().enumerate() {
        let (shape, record) = record?;
        let ed = match record.get("ed") {
            Some(FieldValue::Character(Some(s))) => match Ed::from_str(s) {
                Ok(e) => Some(e),
                _ => None,
            },
            _ => None,
        };
        let geometry = match shape {
            Shape::Polygon(polygon) => {
                let exterior: Vec<_> = polygon
                    .ring(0)
                    .unwrap()
                    .points()
                    .iter()
                    .map(|p| coord! { x: p.x, y: p.y })
                    .collect();
                Some(Polygon::new(exterior.into(), vec![]))
            }
            _ => None, // Skip non-polygon shapes
        };
        let feature = Feature {
            ed,
            geometry,
            properties: record,
            index: i,
        };
        features.push(feature);
    }

    Ok(features)

}
```

**Comment by michaelkirk** [comment]
Take another look at the example I linked: 

https://github.com/tmontaigu/shapefile-rs/blob/master/examples/geotype-example/src/main.rs#L16C7-L16C66

The `shapefile-rs` crate has an [optional `geo-types` feature](https://github.com/tmontaigu/shapefile-rs/blob/master/Cargo.toml#L17) that includes built in conversions.

**Comment by michaelkirk** [comment]
I think a geozero based approach *could* work, but I think you'd have to get more familiar with the geozero processing APIs and implement your own processor to achieve what you're asking. 

Relatedly I think, @frewsxc recently requested a geozero based iterator to take geojson and yield: `(geo::Geometry, HashMap<String, ColumnValue>)`. If some enterprising coder wants to take it on, it seems like it might also work for you.

**Comment by nk9** [comment]
OMG, it works!

```rust
        let geometry = Geometry::<f64>::try_from(shape).ok();
```

I did find this reference to converting between the two shape styles easily, but the docs make no mention of the fact that this API is gated by feature flags. 🙄  Time for a `shapefile-rs` PR, methinks.

Thank you very much for your help!

**Comment by michaelkirk** [comment]
> Time for a shapefile-rs PR, methinks.

Yeah please do!
