### ISSUE TITLE
geojson: should omit `name` field when dataset name is None

### ISSUE THREAD

**Issue by michaelkirk** [georust/geozero#27]
Is there any value in including the blank `name` property? 

I think we should do:
```diff
{ 
  "type": "FeatureCollection",
- "name": "",
  "features": [ ...]
}
```

**Comment by pka** [comment]
I can't remember any good reason for a blank `name`, so fine with omitting.

**Comment by michaelkirk** [comment]
Ok, I'll follow up with a PR momentarily.
