### ISSUE TITLE
end to end PostGIS example

### ISSUE THREAD

**Issue by michaelkirk** [georust/geozero#4]
I see there is a WKB reader/writer and the README mentions support for PostGIS, but it's not obvious to me how to actually wire everything up. 

Is there a working postgis example somewhere?

**Comment by pka** [comment]
Currently, examples are hidden in tests like https://github.com/georust/geozero/blob/master/geozero-core/tests/postgis.rs#L30

Will add a top-level chapter for it after implementing a geo-types reader, which is needed for PostGIS writing.

**Comment by pka** [comment]
https://github.com/georust/geozero#postgis-usage-examples

**Comment by michaelkirk** [comment]
Excellent - thank you!
