### ISSUE TITLE
Using this crate to do bulk inserts with sqlx

### ISSUE THREAD

**Issue by erikpols** [georust/geozero#40]
Hi, 
Would it be possible to use this crate to do bulk inserts as described by the FAQ section of SQLX?
https://github.com/launchbadge/sqlx/blob/master/FAQ.md#how-can-i-bind-an-array-to-a-values-clause-how-can-i-do-bulk-inserts

I'm having trouble with type casting the geometry arrays.

**Comment by pka** [comment]
I've added an example in https://github.com/georust/geozero/blob/ed1d7c4347dabdee1d82f52c0d141220e19e5752/geozero/tests/postgis.rs#L230

It is required to impl `PgHasArrayType` for WKB geometries, which will be available in geozero 0.9.4

**Comment by erikpols** [comment]
that's very cool man! any indication when 0.9.5 will be available? Just asking so I can take it into account with our planning.

**Comment by pka** [comment]
No plan yet. Can be days or weeks.
