### ISSUE TITLE
Add czml support

### ISSUE THREAD

**Issue by constlhq** [georust/geozero#94]
[https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Guide](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Guide)

**Comment by pka** [comment]
What usage scenarios of geozero do see? I could think of creating CZML from 3D PostGIS data, but where would the styling information come from? Or extracting 3D data from CZML?

**Comment by constlhq** [comment]
I didn't think it through neither, I used to create czml file with czml-writer in java, the styling information was setting throuhg interface providered by the package. recently I was learning  rust, so I  wonder  if you have plan to support czml.

**Comment by pka** [comment]
There is no plan fur supporting czml, since it doesn't fit well in the geozero data model and the format is not widely used. But when there is a broad demand for czml, we could reconsider that.

**Comment by constlhq** [comment]
Get it, thanks for reply. I'll close this issue.
